### ISSUE TITLE
Todo list (What I currently want to get done before I move on to power-ups)

### ISSUE THREAD

**Issue by Weirdodude101** [Weirdodude101/MB-Unity-Remake#2]
- [x] Make Item Blocks give items
- [x] Blocks have to do that bouncing thing
- [x] Essentially rewrite Koopas since the code is awful
- [x] Mario should sprint
- [ ] Make jumping relative to how space is hit
- [x] Make the camera more like the original game
- [x] Create the top HUD
